-- Custom Access Token Hook removed.
-- Session enrichment (persona_id, memberships) is handled in src/lib/auth.ts
-- via direct DB queries as fallback (works on Supabase free plan).
-- Hook can be re-added when upgrading to Team plan.
