ALTER TABLE personas
  ADD COLUMN IF NOT EXISTS dni       TEXT,
  ADD COLUMN IF NOT EXISTS direccion TEXT;

ALTER TABLE alumnos
  ADD COLUMN IF NOT EXISTS dni       TEXT,
  ADD COLUMN IF NOT EXISTS telefono  TEXT,
  ADD COLUMN IF NOT EXISTS direccion TEXT;
